mysqlConfigOrderSystem:
  acquireIncrement: 2
  driverClass: com.mysql.jdbc.Driver
  idleConnectionTestPeriodInSeconds: 100
  idleMaxAgeInSeconds: 100
  jdbcUrl: "jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB_NAME}?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true&useSSL=false"
  maxConnectionsPerPartition: 10
  minConnectionsPerPartition: 10
  partitionCount: 2
  password: ${MYSQL_PASSWORD}
  statementsCacheSize: 10
  user: ${MYSQL_ORDER_SYSTEM_USER_NAME}